version: "3"

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  app:
    container_name: app
    image: qloud77/dital-laravel
    ports:
      - 80:8080
    networks:
      - dital

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /dital/mysql:/var/lib/mysql
    restart: always
    ports:
      - "33060:3306"
    networks:
      - dital
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dital
      MYSQL_DATABASE: dital
      MYSQL_PASSWORD: dital

networks:
  dital:
    external: true
